### ISSUE TITLE
Angular 13 & 14

### ISSUE THREAD

**Issue by mfp22** [justindujardin/angular-rpg#28]
If this repo upgrades to Angular 14, I would like to make a YouTube series where I refactor the state management into a more reactive pattern than standard NgRx, and then from that to StateAdapt. I might open a PR to compare, then close it.

If nobody else has the bandwidth, I might do this. But I'm not familiar with this codebase.

**Comment by justindujardin** [comment]
Thanks for reminding me to upgrade the repo for the latest version of Angular. I did that a few weeks ago, hope you enjoy it.

I'm not sure about the refactor you suggested being useful, but if it's a fun exercise for you, what could it hurt? The app is already pretty heavily performance optimized using NgRx and Immutable.js so that it runs well on mobile devices, so you'll want to do some analysis to make sure any refactor keeps the same performance.

If you wanted to refactor something that would be helpful to the project as it is right now, our use of NgRX and RXJS in angular components is outdated. Specifically, the `@Effect` decorator from ngrx/effects and the way we use `combineLatest` from rxjs are deprecated. A refactor to remove the use of those deprecated apis would be very helpful.

I'll close this for now since Angular was updated. Thanks again!
