### ISSUE TITLE
First boss doesn't respond

### ISSUE THREAD

**Issue by mfp22** [justindujardin/angular-rpg#29]
I can come back and add more detail to this issue later when I'm looking at this again, but I'll start with a basic description for now.

On both mobile and desktop, after I played through the first world or whatever it's called, I got to the big building and no monsters appeared and the boss at the end of the red carpet just stood there and ignored me. In the console on desktop it often says "can't read interaction id of undefined" or something along those lines. I can't open the chest in the lower-right room either.

**Comment by Stromwerk** [comment]
I noticed this as well. After some diggin my suspicion is that the entities are simply not found for those encounters. I was able to find entities for the previous fixed encounters (the kobolds, snakes, etc.) but not for the encounters after that one. They are present but only in XML files, not in the "database".

**Comment by justindujardin** [comment]
Thanks for the report. It turns out that you both reached the end of what was implemented. This game was originally based on another, so there's more world and maps/quests to explore, but not many quests/bosses/items/encounters work. 

I went ahead and [fixed the Goblin King boss fight and added the quest reward](https://github.com/justindujardin/angular-rpg/pull/31) that lets you unlock something cool when you return to the port town and tell them of you victory. You can now explore the world some more, but there's not much left other than some enemy encounters. If either of you want to help fix up the later quests, that would be welcomed.

I'll close this as fixed for now but let me know if it's still broken for you. Sadly, you might need to reset your save file to get these fixes.
